#!/bin/bash

# Find the PID of the 7-highlander process
PID=$(pgrep -x "7-highlander")

# Check if the PID was found
if [ -n "$PID" ]; then
    # Kill the process with SIGKILL (signal 9)
    kill -9 "$PID"
    echo "7-highlander process (PID: $PID) has been killed with SIGKILL."
else
    echo "7-highlander process not found."
fi
